version: "2.4"

services:
  mmz-prometheus:
    image: bitnami/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/opt/bitnami/prometheus/data
      - ./prometheus/prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml
    networks:
      - prometheus-back

  mmz-grafana:
    image: bitnami/grafana:latest
    ports:
      - 3000:3000
    volumes:
      - ./grafana/data:/opt/bitnami/grafana/data
      # - ./grafana/grafana.ini:/opt/bitnami/grafana/conf/grafana.ini
    networks:
      - prometheus-back
#    dns:
#      - hostname:'mmz-prometheus.okb-as.ru'

networks:
  prometheus-back:
    driver: bridge
