version: "2.4"

services:
  prometheus:
    image: bitnami/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/opt/bitnami/prometheus/data
      - ./prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml
    networks:
      - prometheus-back

  grafana:
    image: bitnami/grafana:latest
    ports:
      - 3000:3000
    volumes:
      - ./grafana/data:/opt/bitnami/grafana/data
    networks:
      - prometheus-back

networks:
  prometheus-back:
    driver: bridge
